"""empty message

Revision ID: aad68b2856df
Revises: 173bda95bdae
Create Date: 2022-03-03 12:08:25.857969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad68b2856df'
down_revision = '173bda95bdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('fuel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'fuel')
    # ### end Alembic commands ###
