"""empty message

Revision ID: dd891b0e2f1a
Revises: 1adec484fc7f
Create Date: 2022-03-02 15:13:28.197455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd891b0e2f1a'
down_revision = '1adec484fc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journeys__users', type_='foreignkey')
    op.drop_constraint(None, 'journeys__users', type_='foreignkey')
    op.create_foreign_key(None, 'journeys__users', 'journey', ['journey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'journeys__users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journeys__users', type_='foreignkey')
    op.drop_constraint(None, 'journeys__users', type_='foreignkey')
    op.create_foreign_key(None, 'journeys__users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'journeys__users', 'journey', ['journey_id'], ['id'])
    # ### end Alembic commands ###
